[package]
name = "sysinfo"
version = "0.11.2"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "Library to get system information such as processes, processors, disks, components and networks"
repository = "https://github.com/GuillaumeGomez/sysinfo"
license = "MIT"
readme = "README.md"

categories = ["filesystem", "os::macos-apis", "os::unix-apis", "os::windows-apis"]

build = "build.rs"

[dependencies]
cfg-if = "0.1"
rayon = "^1.0"
doc-comment = "0.3"
once_cell = "1.0"
walkdir = "2.2.9"
pnet_datalink = "0.23.0"
num_cpus = "1.11.1"
cache-size = "0.5.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "handleapi", "ifdef", "ioapiset", "minwindef", "pdh", "psapi", "synchapi", "sysinfoapi", "winbase", "winerror", "winioctl", "winnt", "oleauto", "wbemcli", "rpcdce", "combaseapi", "objidl", "objbase", "powerbase", "netioapi"] }
ntapi = "0.3"

[target.'cfg(not(any(target_os = "unknown", target_arch = "wasm32")))'.dependencies]
libc = "0.2"

[lib]
name = "sysinfo"
crate_type = ["rlib", "cdylib"]
path = "src/sysinfo.rs"

[features]
c-interface = []
debug = ["libc/extra_traits"]

[badges]
travis-ci = { repository = "GuillaumeGomez/sysinfo" }
appveyor = { repository = "GuillaumeGomez/sysinfo", service = "github" }
